# Generated by Django 6.0.3 on 2026-03-21 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Turkish')], max_length=2)),
                ('lemma', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180)),
                ('pronunciation_text', models.CharField(blank=True, max_length=200)),
                ('pronunciation_audio_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lemma'],
                'indexes': [models.Index(fields=['language', 'lemma'], name='dictionary__languag_1d7853_idx'), models.Index(fields=['language', 'slug'], name='dictionary__languag_37248e_idx'), models.Index(fields=['language', 'is_active'], name='dictionary__languag_e6e2c8_idx')],
                'unique_together': {('language', 'lemma')},
            },
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('noun', 'İsim'), ('verb', 'Fiil'), ('adj', 'Sıfat'), ('adv', 'Zarf'), ('pron', 'Zamir'), ('prep', 'Edat'), ('conj', 'Bağlaç'), ('interj', 'Ünlem'), ('phrase', 'İfade'), ('other', 'Diğer')], default='other', max_length=10)),
                ('translation', models.CharField(max_length=250)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('is_primary', models.BooleanField(default=False)),
                ('headword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='dictionary.headword')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_source', models.TextField()),
                ('sentence_target', models.TextField()),
                ('audio_url', models.URLField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dictionary.sense')),
            ],
            options={
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrEnLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('en_headword', models.ForeignKey(limit_choices_to={'language': 'en'}, on_delete=django.db.models.deletion.CASCADE, related_name='en_from_tr_links', to='dictionary.headword')),
                ('tr_headword', models.ForeignKey(limit_choices_to={'language': 'tr'}, on_delete=django.db.models.deletion.CASCADE, related_name='tr_to_en_links', to='dictionary.headword')),
            ],
            options={
                'ordering': ['rank', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sense',
            index=models.Index(fields=['headword', 'order_index'], name='dictionary__headwor_c18c45_idx'),
        ),
        migrations.AddIndex(
            model_name='examplesentence',
            index=models.Index(fields=['sense', 'order_index'], name='dictionary__sense_i_0c37d0_idx'),
        ),
        migrations.AddIndex(
            model_name='trenlink',
            index=models.Index(fields=['tr_headword', 'rank'], name='dictionary__tr_head_f360ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trenlink',
            unique_together={('tr_headword', 'en_headword')},
        ),
    ]
