# Generated by Django 6.0.3 on 2026-03-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('home_top', 'Ana Sayfa Ust'), ('en_tr_inline', 'EN-TR Detay Ic'), ('tr_en_bottom', 'TR-EN Detay Alt')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('ad_code', models.TextField(blank=True, help_text='Reklam script/html kodu. Bos ise placeholder metni gosterilir.')),
                ('placeholder_text', models.CharField(default='Reklam alani', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
