# Generated by Django 6.0.3 on 2026-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_seed_mobile_adslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='adslot',
            name='click_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslot',
            name='impression_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adslot',
            name='target_url',
            field=models.URLField(blank=True, help_text='Opsiyonel takipli reklam linki. Doluysa "Reklama git" baglantisi gosterilir.'),
        ),
        migrations.AlterField(
            model_name='adslot',
            name='key',
            field=models.CharField(choices=[('home_top', 'Ana Sayfa Ust'), ('home_top_mobile', 'Ana Sayfa Ust (Mobil)'), ('home_bottom', 'Ana Sayfa Alt'), ('home_bottom_mobile', 'Ana Sayfa Alt (Mobil)'), ('en_tr_inline', 'EN-TR Detay Ic'), ('en_tr_inline_mobile', 'EN-TR Detay Ic (Mobil)'), ('tr_en_bottom', 'TR-EN Detay Alt'), ('tr_en_bottom_mobile', 'TR-EN Detay Alt (Mobil)')], max_length=40, unique=True),
        ),
    ]
