# Generated by Django 6.0.3 on 2026-03-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_adslot_click_count_adslot_impression_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSlotDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('ad_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='dictionary.adslot')),
            ],
            options={
                'ordering': ['-day', 'ad_slot__key'],
                'unique_together': {('ad_slot', 'day')},
            },
        ),
    ]
