# Generated by Django 6.0.3 on 2026-04-05 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_adslotdailystat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='definition',
            field=models.TextField(blank=True, help_text='Ingilizce tanim. Rich text desteklenir.'),
        ),
        migrations.AddField(
            model_name='sense',
            name='grammar_code',
            field=models.CharField(blank=True, help_text='Gramer kodu, ör: [C/U], [T], [I], [singular/U]', max_length=40),
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_text', models.CharField(help_text='Deyim/kalip metni, ör: at/from a distance', max_length=300)),
                ('definition', models.TextField(blank=True, help_text='Ingilizce tanim. Rich text desteklenir.')),
                ('translation', models.CharField(blank=True, help_text='Turkce karsiligi', max_length=300)),
                ('example_source', models.TextField(blank=True)),
                ('example_target', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField(default=1)),
                ('headword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='dictionary.headword')),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'indexes': [models.Index(fields=['headword', 'order_index'], name='dictionary__headwor_b2e773_idx')],
            },
        ),
    ]
