# Generated by Django 6.0.3 on 2026-04-09 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_sense_definition_sense_grammar_code_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosGroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_of_speech', models.CharField(choices=[('noun', 'İsim'), ('verb', 'Fiil'), ('adj', 'Sıfat'), ('adv', 'Zarf'), ('pron', 'Zamir'), ('prep', 'Edat'), ('conj', 'Bağlaç'), ('interj', 'Ünlem'), ('phrase', 'İfade'), ('other', 'Diğer')], max_length=10)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('headword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_group_orders', to='dictionary.headword')),
            ],
            options={
                'ordering': ['order_index', 'id'],
                'unique_together': {('headword', 'part_of_speech')},
            },
        ),
    ]
