# Generated by Django 6.0.3 on 2026-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_pos_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sense',
            name='tr_keywords',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış Türkçe arama terimleri, ör: terk etmek, bırakıp gitmek'),
        ),
    ]
