# Generated by Django 6.0.3 on 2026-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_sense_tr_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='posgrouporder',
            name='irregular_forms',
            field=models.CharField(blank=True, help_text='Düzensiz haller, ör: fly-flew-flown veya plural: flies', max_length=200),
        ),
        migrations.AlterField(
            model_name='posgrouporder',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'İsim'), ('verb', 'Fiil'), ('adj', 'Sıfat'), ('adv', 'Zarf'), ('pron', 'Zamir'), ('prep', 'Edat'), ('conj', 'Bağlaç'), ('interj', 'Ünlem'), ('phr_verb', 'Phrasal Verb'), ('idiom', 'Deyim'), ('saying', 'Atasözü'), ('phrase', 'İfade'), ('other', 'Diğer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sense',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', 'İsim'), ('verb', 'Fiil'), ('adj', 'Sıfat'), ('adv', 'Zarf'), ('pron', 'Zamir'), ('prep', 'Edat'), ('conj', 'Bağlaç'), ('interj', 'Ünlem'), ('phr_verb', 'Phrasal Verb'), ('idiom', 'Deyim'), ('saying', 'Atasözü'), ('phrase', 'İfade'), ('other', 'Diğer')], default='other', max_length=10),
        ),
    ]
