# Generated by Django 6.0.3 on 2026-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_posgrouporder_irregular_forms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Tureng Sözlük', help_text='Tarayıcı başlığında ve üst bantta görünen site adı.', max_length=100)),
                ('brand_tagline', models.CharField(blank=True, default='İngilizce-Türkçe sözlük ve çeviri asistanı.', help_text='Ana sayfa hero alanında logonun altında görünen kısa açıklama.', max_length=250)),
                ('logo_url', models.CharField(blank=True, help_text='Üst bant logosu için URL (opsiyonel). Boşsa statik logo kullanılır.', max_length=300)),
                ('announcement_text', models.CharField(blank=True, help_text='Üst bantta (sarı şerit) gösterilecek duyuru metni. Boşsa bant gizlenir.', max_length=300)),
                ('announcement_link_url', models.URLField(blank=True, help_text='Duyuruya tıklanınca gidilecek URL (opsiyonel).')),
                ('announcement_is_active', models.BooleanField(default=False, help_text='Duyuru bandı açık mı?')),
                ('footer_meta_text', models.CharField(blank=True, default='', help_text='Ana sayfa altında görünen kısa bilgi/meta metni (opsiyonel).', max_length=400)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site ayarı',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
    ]
